apiVersion: v1
kind: Namespace
metadata:
  name: rosa-create-ci 
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-logging: "true"
    openshift.io/cluster-monitoring: "true"
