apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
namespace: sample-blog

resources:
#- django-configmap.yaml
- django-deployment.yaml
- django-secret.yaml
- django-service.yaml
- mysql-configmap.yaml
- mysql-secret.yaml
- mysql-service.yaml
- mysql-pvc.yaml
- mysql-statefulset.yaml
- nginx-deployment.yaml
#- nginx-route.yaml
- nginx-service.yaml
- redis-configmap.yaml
- redis-service.yaml
- redis-pvc.yaml
- redis-statefulset.yaml
- sample-blog-sa.yaml
#- network-policy.yaml
