apiVersion: v1
kind: Namespace
metadata:
  name: sample-blog
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-logging: "true"
    openshift.io/cluster-monitoring: "true"
